/* =========================================================================
 *  인물 얼굴 특징표 —  181명 전원 등재.  이름 해시로 얼굴을 뽑던 구조는 폐기했다.
 *
 *  ── 뼈대(개인차의 핵심) ─────────────────────────────────────────────
 *  headW 38~60   얼굴 폭          headH 42~64   얼굴 길이
 *  face  0둥근 1긴 2네모 3턱넓은 4여윈           jaw 0둥근 1각진 2뾰족
 *  jawWidthMul   0.85~1.15  턱 폭 계수(같은 face 안에서도 인상을 가른다)
 *  eyeSpacing    -3~+3      눈 간격            browHeight -2~+2  눈썹과 눈 사이
 *  cheekY        -0.04~0.04 광대 높이          yaw -6~+6  고개 돌린 각도
 *  noseLenOverride  코 길이 미세 조정
 *
 *  ── 이목구비 ───────────────────────────────────────────────────────
 *  eye   open big thin sharp gentle closed smile glare sanpaku sleepy / patch(안대)
 *  brow  arch flat raised drooped thick          nose straight hook wide long small
 *  mouth closed firm frown open smile            beard none mustache goatee full
 *                                                      long bushy whitelong whisker
 *  hat   topknot gwan helm silk warcloth crown daoist feather phoenixhelm wrap fur
 *        facehelm bare
 *  shoulder robe scale mail pauldron fur court
 *  skin  red dark pale tan bronze sallow         hair black brown gray white
 *  색    green red crimson blue teal purple gold yellow white black brown silver iron
 *  bgStyle 0위밝음 1아래밝음 2후광 3대각 4가로띠 5옆
 *
 *  저작 근거는 docs/faces-notes.md 에 한 줄씩 적어 두었다.
 * ========================================================================= */
const FACES = {

  /* ═══ 위(魏) ═══════════════════════════════════════════════════════ */
  '조조':   { headW: 50, headH: 47, face: 2, jaw: 1, jawWidthMul: 1.02, eyeSpacing: -1, cheekY: -0.02, yaw: -2,
              skin: 'tan', hair: 'black', eye: 'thin', brow: 'raised', nose: 'straight', mouth: 'firm',
              beard: 'mustache', hat: 'crown', color: 'gold', robe: 'crimson', bg: 'crimson', bgStyle: 2, shoulder: 'court' },
  '하후돈': { headW: 54, headH: 52, face: 2, jaw: 1, jawWidthMul: 1.10, eyeSpacing: 1, browHeight: -1, yaw: 3,
              skin: 'bronze', hair: 'black', eye: 'patch', nose: 'wide', mouth: 'firm', browBushy: 1,
              beard: 'full', hat: 'helm', color: 'iron', robe: 'black', bg: 'brown', bgStyle: 0, scar: 1 },
  '하후연': { headW: 47, headH: 55, face: 1, jaw: 1, jawWidthMul: 1.06, eyeSpacing: -2, cheekY: 0.02, yaw: -4,
              skin: 'bronze', hair: 'black', eye: 'sharp', nose: 'long', mouth: 'firm',
              beard: 'goatee', hat: 'helm', color: 'silver', robe: 'blue', bg: 'blue', bgStyle: 3 },
  '조인':   { headW: 55, headH: 51, face: 3, jaw: 1, jawWidthMul: 1.12, eyeSpacing: 2, browHeight: 1, yaw: 0,
              skin: 'tan', hair: 'black', eye: 'open', nose: 'wide', mouth: 'closed',
              beard: 'full', hat: 'helm', color: 'iron', robe: 'crimson', bg: 'crimson', bgStyle: 4 },
  '조홍':   { headW: 56, headH: 45, face: 0, jaw: 0, jawWidthMul: 1.08, eyeSpacing: 1, cheekY: 0.03, yaw: 2,
              skin: 'tan', hair: 'black', eye: 'thin', nose: 'wide', mouth: 'frown',
              beard: 'goatee', hat: 'helm', color: 'bronze', robe: 'red', bg: 'red', bgStyle: 1, fat: 1 },
  '악진':   { headW: 43, headH: 46, face: 2, jaw: 1, jawWidthMul: 1.04, eyeSpacing: -2, browHeight: -2, yaw: -3,
              skin: 'bronze', hair: 'black', eye: 'sharp', nose: 'small', mouth: 'firm',
              beard: 'mustache', hat: 'helm', color: 'steel', robe: 'brown', bg: 'brown', bgStyle: 0 },
  '이전':   { headW: 46, headH: 54, face: 1, jaw: 0, jawWidthMul: 0.94, eyeSpacing: 0, browHeight: 1, yaw: 1,
              skin: 'pale', hair: 'black', eye: 'gentle', nose: 'straight', mouth: 'closed',
              beard: 'goatee', hat: 'silk', color: 'blue', robe: 'blue', bg: 'teal', bgStyle: 2 },
  '우금':   { headW: 50, headH: 53, face: 2, jaw: 1, jawWidthMul: 1.05, eyeSpacing: -1, browHeight: -1, yaw: 0,
              skin: 'tan', hair: 'black', eye: 'glare', brow: 'flat', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'iron', robe: 'teal', bg: 'teal', bgStyle: 0 },
  '서황':   { headW: 48, headH: 58, face: 1, jaw: 1, jawWidthMul: 1.00, eyeSpacing: -1, cheekY: -0.03, yaw: -2,
              skin: 'bronze', hair: 'black', eye: 'thin', nose: 'long', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'steel', robe: 'brown', bg: 'gold', bgStyle: 3 },
  '장료':   { headW: 51, headH: 56, face: 1, jaw: 1, jawWidthMul: 1.03, eyeSpacing: 0, browHeight: -1, yaw: -3,
              skin: 'tan', hair: 'brown', eye: 'sharp', nose: 'straight', mouth: 'firm', browBushy: 1,
              beard: 'full', hat: 'helm', color: 'silver', robe: 'blue', bg: 'blue', bgStyle: 2 },
  '서저':   { headW: 60, headH: 50, face: 3, jaw: 1, jawWidthMul: 1.15, eyeSpacing: 3, browHeight: -2, yaw: 1,
              skin: 'bronze', hair: 'black', eye: 'big', nose: 'wide', mouth: 'open', irisDark: 1,
              beard: 'bushy', hat: 'topknot', color: 'brown', robe: 'brown', bg: 'brown', bgStyle: 4 },
  '전위':   { headW: 58, headH: 53, face: 3, jaw: 1, jawWidthMul: 1.13, eyeSpacing: 2, browHeight: -2, yaw: -1,
              skin: 'dark', hair: 'black', eye: 'glare', nose: 'wide', mouth: 'open', browBushy: 1,
              beard: 'bushy', hat: 'bare', robe: 'black', bg: 'black', bgStyle: 0, scar: 1 },
  '순욱':   { headW: 43, headH: 58, face: 4, jaw: 2, jawWidthMul: 0.88, eyeSpacing: -1, browHeight: 2, yaw: 2,
              skin: 'pale', hair: 'black', eye: 'gentle', nose: 'straight', mouth: 'closed',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'white', bg: 'teal', bgStyle: 2 },
  '순유':   { headW: 46, headH: 54, face: 4, jaw: 2, jawWidthMul: 0.90, eyeSpacing: 1, browHeight: 1, yaw: -1,
              skin: 'pale', hair: 'black', eye: 'sleepy', nose: 'straight', mouth: 'closed',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'purple', bg: 'purple', bgStyle: 5 },
  '곽가':   { headW: 40, headH: 56, face: 4, jaw: 2, jawWidthMul: 0.85, eyeSpacing: 0, browHeight: 2, yaw: -3,
              skin: 'pale', hair: 'black', eye: 'thin', brow: 'arch', nose: 'straight', mouth: 'smile',
              beard: 'none', hat: 'silk', color: 'white', robe: 'teal', bg: 'teal', bgStyle: 2, young: 1 },
  '정욱':   { headW: 50, headH: 63, face: 1, jaw: 1, jawWidthMul: 0.98, eyeSpacing: -2, browHeight: 0, yaw: 1,
              skin: 'tan', hair: 'black', eye: 'glare', nose: 'long', mouth: 'firm',
              beard: 'long', beardLen: 22, hat: 'gwan', color: 'black', robe: 'brown', bg: 'brown', bgStyle: 0 },
  '유엽':   { headW: 45, headH: 52, face: 4, jaw: 2, jawWidthMul: 0.92, eyeSpacing: 2, browHeight: 1, yaw: 0,
              skin: 'pale', hair: 'black', eye: 'closed', nose: 'small', mouth: 'closed',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'green', bg: 'green', bgStyle: 3 },
  '만총':   { headW: 49, headH: 50, face: 2, jaw: 1, jawWidthMul: 1.04, eyeSpacing: -3, browHeight: -1, yaw: 2,
              skin: 'tan', hair: 'black', eye: 'glare', brow: 'flat', nose: 'straight', mouth: 'frown',
              beard: 'mustache', hat: 'gwan', color: 'black', robe: 'blue', bg: 'blue', bgStyle: 4 },
  '방덕':   { headW: 52, headH: 52, face: 2, jaw: 1, jawWidthMul: 1.07, eyeSpacing: 0, browHeight: -1, yaw: -4,
              skin: 'bronze', hair: 'brown', eye: 'sharp', nose: 'hook', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'iron', robe: 'white', bg: 'gold', bgStyle: 0 },
  '장합':   { headW: 47, headH: 55, face: 1, jaw: 2, jawWidthMul: 0.96, eyeSpacing: 1, cheekY: -0.02, yaw: 3,
              skin: 'pale', hair: 'black', eye: 'thin', nose: 'long', mouth: 'closed',
              beard: 'goatee', hat: 'helm', color: 'silver', robe: 'purple', bg: 'purple', bgStyle: 2 },
  '문빙':   { headW: 49, headH: 51, face: 0, jaw: 0, jawWidthMul: 1.01, eyeSpacing: 0, browHeight: 0, yaw: -2,
              skin: 'tan', hair: 'black', eye: 'open', nose: 'straight', mouth: 'closed',
              beard: 'full', hat: 'warcloth', color: 'green', robe: 'green', bg: 'green', bgStyle: 1 },
  '조휴':   { headW: 46, headH: 50, face: 0, jaw: 0, jawWidthMul: 1.06, eyeSpacing: -1, browHeight: 1, yaw: 4,
              skin: 'pale', hair: 'black', eye: 'open', nose: 'straight', mouth: 'smile',
              beard: 'mustache', hat: 'phoenixhelm', color: 'silver', robe: 'crimson', bg: 'red', bgStyle: 2, young: 1 },
  '조진':   { headW: 52, headH: 49, face: 2, jaw: 1, jawWidthMul: 1.09, eyeSpacing: 1, browHeight: -1, yaw: 0,
              skin: 'tan', hair: 'black', eye: 'sharp', nose: 'wide', mouth: 'firm',
              beard: 'full', hat: 'facehelm', color: 'iron', robe: 'crimson', bg: 'crimson', bgStyle: 0 },
  '사마의': { headW: 46, headH: 59, face: 1, jaw: 2, jawWidthMul: 0.93, eyeSpacing: -2, browHeight: 2, cheekY: 0.03, yaw: -5,
              skin: 'pale', hair: 'gray', eye: 'thin', brow: 'raised', nose: 'hook', mouth: 'firm',
              beard: 'long', beardLen: 18, hat: 'gwan', color: 'black', robe: 'purple', bg: 'purple', bgStyle: 2 },
  '등애':   { headW: 51, headH: 54, face: 2, jaw: 1, jawWidthMul: 1.02, eyeSpacing: 2, browHeight: 0, yaw: 1,
              skin: 'bronze', hair: 'gray', eye: 'sanpaku', nose: 'wide', mouth: 'open',
              beard: 'full', hat: 'helm', color: 'bronze', robe: 'brown', bg: 'brown', bgStyle: 3 },
  '종회':   { headW: 44, headH: 55, face: 4, jaw: 2, jawWidthMul: 0.89, eyeSpacing: -1, browHeight: 1, yaw: -2,
              skin: 'pale', hair: 'black', eye: 'sharp', brow: 'raised', nose: 'straight', mouth: 'smile',
              beard: 'none', hat: 'gwan', color: 'purple', robe: 'purple', bg: 'black', bgStyle: 2, young: 1 },
  '학소':   { headW: 53, headH: 47, face: 3, jaw: 1, jawWidthMul: 1.11, eyeSpacing: 1, browHeight: -2, yaw: 2,
              skin: 'bronze', hair: 'black', eye: 'glare', nose: 'wide', mouth: 'firm', browBushy: 1,
              beard: 'bushy', hat: 'helm', color: 'steel', robe: 'iron', bg: 'silver', bgStyle: 4 },
  '진태':   { headW: 48, headH: 53, face: 1, jaw: 0, jawWidthMul: 0.99, eyeSpacing: 0, browHeight: 0, yaw: -1,
              skin: 'pale', hair: 'black', eye: 'thin', nose: 'straight', mouth: 'closed',
              beard: 'goatee', hat: 'helm', color: 'blue', robe: 'blue', bg: 'teal', bgStyle: 5 },
  '이통':   { headW: 51, headH: 48, face: 2, jaw: 1, jawWidthMul: 1.05, eyeSpacing: 2, browHeight: -1, yaw: 3,
              skin: 'dark', hair: 'black', eye: 'big', nose: 'wide', mouth: 'open',
              beard: 'whisker', hat: 'warcloth', color: 'brown', robe: 'brown', bg: 'brown', bgStyle: 1 },
  '여건':   { headW: 50, headH: 52, face: 0, jaw: 0, jawWidthMul: 1.00, eyeSpacing: -1, browHeight: 1, yaw: -2,
              skin: 'tan', hair: 'black', eye: 'open', nose: 'straight', mouth: 'closed',
              beard: 'full', hat: 'helm', color: 'steel', robe: 'green', bg: 'green', bgStyle: 0 },
  '전예':   { headW: 47, headH: 51, face: 1, jaw: 0, jawWidthMul: 0.97, eyeSpacing: 1, browHeight: 0, yaw: 4,
              skin: 'bronze', hair: 'brown', eye: 'gentle', nose: 'straight', mouth: 'closed',
              beard: 'goatee', hat: 'fur', color: 'brown', robe: 'brown', bg: 'silver', bgStyle: 5 },
  '가후':   { headW: 45, headH: 57, face: 4, jaw: 2, jawWidthMul: 0.87, eyeSpacing: -3, browHeight: 2, cheekY: 0.02, yaw: 5,
              skin: 'sallow', hair: 'gray', eye: 'closed', nose: 'hook', mouth: 'smile',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'black', bg: 'black', bgStyle: 2 },
  '하후패': { headW: 50, headH: 54, face: 1, jaw: 1, jawWidthMul: 1.06, eyeSpacing: 0, browHeight: -1, yaw: -3,
              skin: 'bronze', hair: 'black', eye: 'sharp', nose: 'long', mouth: 'frown',
              beard: 'full', hat: 'helm', color: 'iron', robe: 'red', bg: 'red', bgStyle: 3 },
  '곽회':   { headW: 49, headH: 53, face: 2, jaw: 0, jawWidthMul: 1.03, eyeSpacing: -2, browHeight: 1, yaw: 1,
              skin: 'tan', hair: 'black', eye: 'thin', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'blue', robe: 'blue', bg: 'blue', bgStyle: 0 },
  '문앙':   { headW: 45, headH: 50, face: 0, jaw: 2, jawWidthMul: 0.95, eyeSpacing: 1, browHeight: -2, yaw: -5,
              skin: 'pale', hair: 'black', eye: 'big', brow: 'raised', nose: 'small', mouth: 'open',
              beard: 'none', hat: 'phoenixhelm', color: 'silver', robe: 'white', bg: 'blue', bgStyle: 2, young: 1 },
  '종요':   { headW: 44, headH: 56, face: 4, jaw: 2, jawWidthMul: 0.91, eyeSpacing: 0, browHeight: 2, yaw: 2,
              skin: 'pale', hair: 'gray', eye: 'gentle', nose: 'straight', mouth: 'closed',
              beard: 'whitelong', beardLen: 17, hat: 'gwan', color: 'black', robe: 'white', bg: 'teal', bgStyle: 1 },
  '조비':   { headW: 47, headH: 54, face: 1, jaw: 2, jawWidthMul: 0.94, eyeSpacing: -2, browHeight: 1, cheekY: -0.03, yaw: -1,
              skin: 'pale', hair: 'black', eye: 'thin', brow: 'raised', nose: 'straight', mouth: 'frown',
              beard: 'mustache', hat: 'crown', color: 'gold', robe: 'crimson', bg: 'crimson', bgStyle: 2 },
  '조예':   { headW: 48, headH: 52, face: 1, jaw: 0, jawWidthMul: 1.00, eyeSpacing: 0, browHeight: 1, yaw: 0,
              skin: 'pale', hair: 'black', eye: 'gentle', nose: 'straight', mouth: 'closed',
              beard: 'goatee', hat: 'crown', color: 'gold', robe: 'purple', bg: 'purple', bgStyle: 2 },
  '사마사': { headW: 49, headH: 57, face: 1, jaw: 1, jawWidthMul: 0.97, eyeSpacing: -1, browHeight: 0, yaw: 3,
              skin: 'pale', hair: 'black', eye: 'glare', brow: 'raised', nose: 'hook', mouth: 'firm',
              beard: 'full', hat: 'gwan', color: 'black', robe: 'black', bg: 'purple', bgStyle: 0, scar: 1 },
  '사마소': { headW: 51, headH: 55, face: 2, jaw: 1, jawWidthMul: 1.01, eyeSpacing: 1, browHeight: -1, yaw: -2,
              skin: 'tan', hair: 'black', eye: 'sanpaku', nose: 'hook', mouth: 'smile',
              beard: 'full', hat: 'crown', color: 'gold', robe: 'black', bg: 'black', bgStyle: 3 },
  '화타':   { headW: 46, headH: 56, face: 4, jaw: 2, jawWidthMul: 0.90, eyeSpacing: 0, browHeight: 2, yaw: -2,
              skin: 'sallow', hair: 'white', eye: 'gentle', nose: 'straight', mouth: 'smile',
              beard: 'whitelong', beardLen: 20, hat: 'silk', color: 'white', robe: 'green', bg: 'green', bgStyle: 2 },

  /* ═══ 촉(蜀) ═══════════════════════════════════════════════════════ */
  '유비':   { headW: 49, headH: 54, face: 1, jaw: 0, jawWidthMul: 0.98, eyeSpacing: 2, browHeight: 1, cheekY: 0.02, yaw: 1,
              skin: 'pale', hair: 'black', eye: 'gentle', brow: 'arch', nose: 'straight', mouth: 'closed',
              beard: 'goatee', hat: 'crown', color: 'gold', robe: 'gold', bg: 'blue', bgStyle: 2, ear: 1 },
  '관우':   { headW: 47, headH: 60, face: 1, jaw: 1, jawWidthMul: 0.99, eyeSpacing: -2, browHeight: 0, cheekY: -0.02, yaw: -3,
              skin: 'red', hair: 'black', eye: 'sharp', brow: 'raised', nose: 'long', mouth: 'firm', browBushy: 1,
              beard: 'long', beardLen: 24, hat: 'warcloth', color: 'green', robe: 'green', bg: 'green', bgStyle: 2 },
  '장비':   { headW: 57, headH: 49, face: 3, jaw: 1, jawWidthMul: 1.14, eyeSpacing: 3, browHeight: -2, yaw: 2,
              skin: 'dark', hair: 'black', eye: 'big', brow: 'thick', nose: 'wide', mouth: 'open',
              beard: 'bushy', hat: 'helm', color: 'iron', robe: 'black', bg: 'crimson', bgStyle: 0, irisDark: 1 },
  '조운':   { headW: 46, headH: 53, face: 1, jaw: 2, jawWidthMul: 0.93, eyeSpacing: -1, browHeight: 0, yaw: -4,
              skin: 'pale', hair: 'black', eye: 'open', brow: 'arch', nose: 'straight', mouth: 'closed',
              beard: 'none', hat: 'phoenixhelm', color: 'silver', robe: 'white', bg: 'teal', bgStyle: 2, young: 1 },
  '제갈량': { headW: 44, headH: 57, face: 4, jaw: 2, jawWidthMul: 0.88, eyeSpacing: -1, browHeight: 2, cheekY: -0.03, yaw: 0,
              skin: 'pale', hair: 'black', eye: 'thin', brow: 'arch', nose: 'straight', mouth: 'closed',
              beard: 'goatee', hat: 'silk', color: 'white', robe: 'white', bg: 'teal', bgStyle: 2, fan: 1 },
  '방통':   { headW: 53, headH: 46, face: 3, jaw: 1, jawWidthMul: 1.10, eyeSpacing: 3, browHeight: -2, cheekY: 0.03, yaw: 4,
              skin: 'sallow', hair: 'black', eye: 'sanpaku', brow: 'thick', nose: 'wide', mouth: 'frown',
              beard: 'bushy', hat: 'silk', color: 'brown', robe: 'brown', bg: 'purple', bgStyle: 4 },
  '황충':   { headW: 52, headH: 51, face: 2, jaw: 1, jawWidthMul: 1.08, eyeSpacing: 0, browHeight: -1, yaw: -2,
              skin: 'bronze', hair: 'white', eye: 'sharp', nose: 'hook', mouth: 'firm', browBushy: 1,
              beard: 'whitelong', beardLen: 19, hat: 'helm', color: 'bronze', robe: 'brown', bg: 'gold', bgStyle: 0 },
  '마초':   { headW: 46, headH: 52, face: 1, jaw: 2, jawWidthMul: 0.92, eyeSpacing: -2, browHeight: -1, yaw: -5,
              skin: 'pale', hair: 'brown', eye: 'sharp', brow: 'raised', nose: 'straight', mouth: 'firm',
              beard: 'none', hat: 'phoenixhelm', color: 'silver', robe: 'white', bg: 'blue', bgStyle: 2, young: 1 },
  '마대':   { headW: 48, headH: 51, face: 1, jaw: 1, jawWidthMul: 1.02, eyeSpacing: 0, browHeight: 0, yaw: 3,
              skin: 'bronze', hair: 'brown', eye: 'open', nose: 'straight', mouth: 'closed',
              beard: 'full', hat: 'warcloth', color: 'brown', robe: 'brown', bg: 'brown', bgStyle: 3 },
  '위연':   { headW: 51, headH: 55, face: 2, jaw: 1, jawWidthMul: 1.06, eyeSpacing: 1, browHeight: -2, cheekY: 0.02, yaw: 2,
              skin: 'bronze', hair: 'black', eye: 'glare', brow: 'raised', nose: 'hook', mouth: 'frown',
              beard: 'full', hat: 'helm', color: 'iron', robe: 'crimson', bg: 'brown', bgStyle: 0, scar: 1 },
  '강유':   { headW: 45, headH: 53, face: 1, jaw: 2, jawWidthMul: 0.94, eyeSpacing: -1, browHeight: 1, yaw: -2,
              skin: 'pale', hair: 'black', eye: 'open', brow: 'arch', nose: 'straight', mouth: 'closed',
              beard: 'mustache', hat: 'helm', color: 'silver', robe: 'blue', bg: 'teal', bgStyle: 2, young: 1 },
  '법정':   { headW: 44, headH: 54, face: 4, jaw: 2, jawWidthMul: 0.89, eyeSpacing: -3, browHeight: 1, yaw: 4,
              skin: 'sallow', hair: 'black', eye: 'glare', brow: 'raised', nose: 'hook', mouth: 'frown',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'purple', bg: 'purple', bgStyle: 5 },
  '서서':   { headW: 46, headH: 55, face: 1, jaw: 0, jawWidthMul: 0.96, eyeSpacing: 0, browHeight: 1, yaw: -1,
              skin: 'tan', hair: 'black', eye: 'sharp', nose: 'straight', mouth: 'closed',
              beard: 'goatee', hat: 'wrap', color: 'blue', robe: 'blue', bg: 'blue', bgStyle: 3 },
  '미축':   { headW: 50, headH: 50, face: 0, jaw: 0, jawWidthMul: 1.04, eyeSpacing: 1, browHeight: 1, yaw: 1,
              skin: 'pale', hair: 'black', eye: 'smile', nose: 'wide', mouth: 'smile',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'gold', bg: 'gold', bgStyle: 1, shoulder: 'court' },
  '손건':   { headW: 47, headH: 52, face: 1, jaw: 0, jawWidthMul: 0.97, eyeSpacing: 0, browHeight: 0, yaw: -2,
              skin: 'tan', hair: 'black', eye: 'gentle', nose: 'straight', mouth: 'smile',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'teal', bg: 'teal', bgStyle: 0 },
  '간옹':   { headW: 45, headH: 50, face: 4, jaw: 2, jawWidthMul: 0.91, eyeSpacing: 2, browHeight: 2, yaw: 5,
              skin: 'pale', hair: 'black', eye: 'smile', brow: 'arch', nose: 'small', mouth: 'smile',
              beard: 'mustache', hat: 'silk', color: 'green', robe: 'green', bg: 'green', bgStyle: 5 },
  '이적':   { headW: 48, headH: 53, face: 1, jaw: 0, jawWidthMul: 0.99, eyeSpacing: -1, browHeight: 1, yaw: 2,
              skin: 'pale', hair: 'black', eye: 'thin', nose: 'straight', mouth: 'closed',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'white', bg: 'blue', bgStyle: 2 },
  '요화':   { headW: 50, headH: 54, face: 2, jaw: 1, jawWidthMul: 1.05, eyeSpacing: 1, browHeight: -1, yaw: -3,
              skin: 'bronze', hair: 'gray', eye: 'open', nose: 'wide', mouth: 'firm',
              beard: 'whitelong', beardLen: 16, hat: 'helm', color: 'steel', robe: 'green', bg: 'brown', bgStyle: 4 },
  '관평':   { headW: 45, headH: 55, face: 1, jaw: 1, jawWidthMul: 0.98, eyeSpacing: -2, browHeight: 0, yaw: -3,
              skin: 'red', hair: 'black', eye: 'sharp', nose: 'long', mouth: 'firm',
              beard: 'none', hat: 'warcloth', color: 'green', robe: 'green', bg: 'teal', bgStyle: 3, young: 1 },
  '관흥':   { headW: 46, headH: 57, face: 1, jaw: 1, jawWidthMul: 1.00, eyeSpacing: -2, browHeight: -1, yaw: -4,
              skin: 'red', hair: 'black', eye: 'sharp', brow: 'raised', nose: 'long', mouth: 'firm',
              beard: 'mustache', hat: 'phoenixhelm', color: 'green', robe: 'green', bg: 'green', bgStyle: 0, young: 1 },
  '장포':   { headW: 54, headH: 50, face: 3, jaw: 1, jawWidthMul: 1.12, eyeSpacing: 2, browHeight: -2, yaw: 3,
              skin: 'dark', hair: 'black', eye: 'big', brow: 'thick', nose: 'wide', mouth: 'open',
              beard: 'full', hat: 'helm', color: 'iron', robe: 'black', bg: 'crimson', bgStyle: 1, young: 1 },
  '왕평':   { headW: 52, headH: 48, face: 2, jaw: 1, jawWidthMul: 1.07, eyeSpacing: 1, browHeight: -1, yaw: 0,
              skin: 'dark', hair: 'black', eye: 'glare', nose: 'wide', mouth: 'firm',
              beard: 'full', hat: 'warcloth', color: 'brown', robe: 'brown', bg: 'gold', bgStyle: 4 },
  '오반':   { headW: 49, headH: 52, face: 0, jaw: 0, jawWidthMul: 1.01, eyeSpacing: 0, browHeight: 0, yaw: -1,
              skin: 'tan', hair: 'black', eye: 'open', nose: 'straight', mouth: 'closed',
              beard: 'full', hat: 'helm', color: 'steel', robe: 'red', bg: 'red', bgStyle: 0 },
  '유봉':   { headW: 48, headH: 51, face: 0, jaw: 1, jawWidthMul: 1.03, eyeSpacing: -1, browHeight: -1, yaw: 2,
              skin: 'tan', hair: 'black', eye: 'sharp', nose: 'straight', mouth: 'frown',
              beard: 'none', hat: 'helm', color: 'bronze', robe: 'gold', bg: 'brown', bgStyle: 3, young: 1 },
  '맹달':   { headW: 47, headH: 53, face: 1, jaw: 2, jawWidthMul: 0.95, eyeSpacing: 2, browHeight: 1, yaw: 4,
              skin: 'pale', hair: 'black', eye: 'sanpaku', nose: 'hook', mouth: 'smile',
              beard: 'goatee', hat: 'wrap', color: 'purple', robe: 'purple', bg: 'purple', bgStyle: 5 },
  '곽준':   { headW: 51, headH: 50, face: 2, jaw: 1, jawWidthMul: 1.06, eyeSpacing: 0, browHeight: 0, yaw: -2,
              skin: 'bronze', hair: 'black', eye: 'open', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'steel', robe: 'teal', bg: 'teal', bgStyle: 1 },
  '장익':   { headW: 47, headH: 54, face: 1, jaw: 1, jawWidthMul: 0.98, eyeSpacing: -1, browHeight: 1, yaw: 1,
              skin: 'tan', hair: 'black', eye: 'thin', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'blue', robe: 'blue', bg: 'blue', bgStyle: 2 },
  '마속':   { headW: 44, headH: 52, face: 4, jaw: 2, jawWidthMul: 0.90, eyeSpacing: -1, browHeight: 2, yaw: -2,
              skin: 'pale', hair: 'black', eye: 'open', brow: 'raised', nose: 'small', mouth: 'smile',
              beard: 'none', hat: 'gwan', color: 'black', robe: 'white', bg: 'green', bgStyle: 2, young: 1 },
  '장완':   { headW: 48, headH: 56, face: 1, jaw: 0, jawWidthMul: 0.96, eyeSpacing: 0, browHeight: 2, yaw: 0,
              skin: 'pale', hair: 'black', eye: 'gentle', nose: 'straight', mouth: 'closed',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'white', bg: 'teal', bgStyle: 1, shoulder: 'court' },
  '비의':   { headW: 46, headH: 53, face: 1, jaw: 2, jawWidthMul: 0.93, eyeSpacing: 1, browHeight: 1, yaw: 3,
              skin: 'pale', hair: 'black', eye: 'smile', nose: 'small', mouth: 'smile',
              beard: 'mustache', hat: 'gwan', color: 'black', robe: 'green', bg: 'green', bgStyle: 3 },
  '동윤':   { headW: 47, headH: 55, face: 1, jaw: 0, jawWidthMul: 0.97, eyeSpacing: -2, browHeight: 1, yaw: -1,
              skin: 'pale', hair: 'black', eye: 'glare', brow: 'flat', nose: 'straight', mouth: 'firm',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'blue', bg: 'purple', bgStyle: 0 },
  '유선':   { headW: 52, headH: 47, face: 0, jaw: 0, jawWidthMul: 1.06, eyeSpacing: 2, browHeight: 2, cheekY: 0.03, yaw: 1,
              skin: 'pale', hair: 'black', eye: 'sleepy', brow: 'drooped', nose: 'small', mouth: 'open',
              beard: 'none', hat: 'crown', color: 'gold', robe: 'gold', bg: 'gold', bgStyle: 2, ear: 1, fat: 1 },

  /* ═══ 오(吳) ═══════════════════════════════════════════════════════ */
  '손견':   { headW: 53, headH: 52, face: 2, jaw: 1, jawWidthMul: 1.09, eyeSpacing: 0, browHeight: -1, yaw: -2,
              skin: 'bronze', hair: 'black', eye: 'sharp', brow: 'thick', nose: 'wide', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'gold', robe: 'red', bg: 'red', bgStyle: 0 },
  '손책':   { headW: 47, headH: 51, face: 0, jaw: 2, jawWidthMul: 1.05, eyeSpacing: -1, browHeight: 0, yaw: -4,
              skin: 'pale', hair: 'black', eye: 'sharp', brow: 'raised', nose: 'straight', mouth: 'smile',
              beard: 'none', hat: 'phoenixhelm', color: 'gold', robe: 'red', bg: 'teal', bgStyle: 2, young: 1 },
  '손권':   { headW: 51, headH: 50, face: 2, jaw: 1, jawWidthMul: 1.07, eyeSpacing: 1, browHeight: 0, cheekY: 0.02, yaw: 1,
              skin: 'pale', hair: 'brown', eye: 'big', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'crown', color: 'gold', robe: 'purple', bg: 'purple', bgStyle: 2 },
  '주유':   { headW: 45, headH: 55, face: 1, jaw: 2, jawWidthMul: 0.91, eyeSpacing: -1, browHeight: 1, cheekY: -0.02, yaw: -3,
              skin: 'pale', hair: 'black', eye: 'sharp', brow: 'arch', nose: 'straight', mouth: 'closed',
              beard: 'mustache', hat: 'gwan', color: 'black', robe: 'white', bg: 'blue', bgStyle: 2, young: 1 },
  '주태':   { headW: 54, headH: 49, face: 3, jaw: 1, jawWidthMul: 1.11, eyeSpacing: 2, browHeight: -2, yaw: 2,
              skin: 'dark', hair: 'black', eye: 'glare', nose: 'wide', mouth: 'firm',
              beard: 'bushy', hat: 'warcloth', color: 'brown', robe: 'brown', bg: 'brown', bgStyle: 4, scar: 1 },
  '감녕':   { headW: 50, headH: 51, face: 2, jaw: 1, jawWidthMul: 1.06, eyeSpacing: 1, browHeight: -2, yaw: -3,
              skin: 'dark', hair: 'black', eye: 'big', brow: 'thick', nose: 'wide', mouth: 'open',
              beard: 'bushy', hat: 'warcloth', color: 'crimson', robe: 'crimson', bg: 'crimson', bgStyle: 0, earring: 1 },
  '태사자': { headW: 48, headH: 56, face: 1, jaw: 1, jawWidthMul: 1.02, eyeSpacing: -2, browHeight: -1, yaw: -4,
              skin: 'tan', hair: 'black', eye: 'sharp', nose: 'long', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'silver', robe: 'green', bg: 'green', bgStyle: 3 },
  '황개':   { headW: 52, headH: 53, face: 2, jaw: 1, jawWidthMul: 1.08, eyeSpacing: 0, browHeight: -1, yaw: 3,
              skin: 'bronze', hair: 'gray', eye: 'glare', nose: 'hook', mouth: 'firm', browBushy: 1,
              beard: 'whitelong', beardLen: 18, hat: 'helm', color: 'bronze', robe: 'red', bg: 'brown', bgStyle: 0 },
  '한당':   { headW: 50, headH: 54, face: 1, jaw: 1, jawWidthMul: 1.04, eyeSpacing: -1, browHeight: 0, yaw: -1,
              skin: 'bronze', hair: 'gray', eye: 'open', nose: 'straight', mouth: 'closed',
              beard: 'full', hat: 'helm', color: 'steel', robe: 'red', bg: 'red', bgStyle: 1 },
  '정보':   { headW: 51, headH: 55, face: 1, jaw: 1, jawWidthMul: 1.03, eyeSpacing: 0, browHeight: 1, yaw: 2,
              skin: 'tan', hair: 'gray', eye: 'gentle', nose: 'straight', mouth: 'closed',
              beard: 'whitelong', beardLen: 16, hat: 'helm', color: 'bronze', robe: 'red', bg: 'gold', bgStyle: 2 },
  '여몽':   { headW: 52, headH: 50, face: 2, jaw: 1, jawWidthMul: 1.05, eyeSpacing: 1, browHeight: 0, yaw: -2,
              skin: 'bronze', hair: 'black', eye: 'open', brow: 'flat', nose: 'wide', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'steel', robe: 'teal', bg: 'teal', bgStyle: 0 },
  '육손':   { headW: 44, headH: 54, face: 4, jaw: 2, jawWidthMul: 0.89, eyeSpacing: -1, browHeight: 2, yaw: -2,
              skin: 'pale', hair: 'black', eye: 'thin', brow: 'arch', nose: 'straight', mouth: 'closed',
              beard: 'none', hat: 'gwan', color: 'black', robe: 'white', bg: 'green', bgStyle: 2, young: 1 },
  '노숙':   { headW: 53, headH: 51, face: 3, jaw: 0, jawWidthMul: 1.09, eyeSpacing: 2, browHeight: 1, cheekY: 0.03, yaw: 1,
              skin: 'pale', hair: 'black', eye: 'gentle', nose: 'wide', mouth: 'smile',
              beard: 'full', hat: 'gwan', color: 'black', robe: 'teal', bg: 'teal', bgStyle: 1 },
  '장소':   { headW: 47, headH: 57, face: 1, jaw: 2, jawWidthMul: 0.94, eyeSpacing: -2, browHeight: 1, yaw: 0,
              skin: 'pale', hair: 'gray', eye: 'glare', brow: 'flat', nose: 'straight', mouth: 'frown',
              beard: 'whitelong', beardLen: 20, hat: 'gwan', color: 'black', robe: 'purple', bg: 'purple', bgStyle: 0, shoulder: 'court' },
  '제갈근': { headW: 43, headH: 62, face: 1, jaw: 2, jawWidthMul: 0.90, eyeSpacing: 0, browHeight: 1, yaw: 2,
              skin: 'pale', hair: 'black', eye: 'gentle', nose: 'long', mouth: 'closed',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'green', bg: 'teal', bgStyle: 3 },
  '서성':   { headW: 49, headH: 52, face: 1, jaw: 1, jawWidthMul: 1.01, eyeSpacing: -1, browHeight: -1, yaw: -3,
              skin: 'tan', hair: 'black', eye: 'sharp', nose: 'straight', mouth: 'firm',
              beard: 'goatee', hat: 'helm', color: 'blue', robe: 'blue', bg: 'blue', bgStyle: 3 },
  '정봉':   { headW: 51, headH: 53, face: 2, jaw: 1, jawWidthMul: 1.07, eyeSpacing: 1, browHeight: -2, yaw: 4,
              skin: 'bronze', hair: 'gray', eye: 'sharp', nose: 'wide', mouth: 'firm', browBushy: 1,
              beard: 'full', hat: 'fur', color: 'brown', robe: 'iron', bg: 'silver', bgStyle: 5 },
  '반장':   { headW: 50, headH: 49, face: 2, jaw: 1, jawWidthMul: 1.06, eyeSpacing: 2, browHeight: -1, yaw: 1,
              skin: 'dark', hair: 'black', eye: 'sanpaku', nose: 'hook', mouth: 'frown',
              beard: 'full', hat: 'warcloth', color: 'yellow', robe: 'yellow', bg: 'gold', bgStyle: 4 },
  '능통':   { headW: 46, headH: 52, face: 1, jaw: 2, jawWidthMul: 0.95, eyeSpacing: -1, browHeight: 0, yaw: -4,
              skin: 'tan', hair: 'black', eye: 'sharp', nose: 'straight', mouth: 'firm',
              beard: 'mustache', hat: 'helm', color: 'silver', robe: 'green', bg: 'green', bgStyle: 2, young: 1 },
  '여범':   { headW: 49, headH: 54, face: 1, jaw: 0, jawWidthMul: 0.99, eyeSpacing: 0, browHeight: 1, yaw: 2,
              skin: 'pale', hair: 'black', eye: 'thin', nose: 'straight', mouth: 'closed',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'gold', bg: 'gold', bgStyle: 1, shoulder: 'court' },
  '고옹':   { headW: 45, headH: 58, face: 4, jaw: 2, jawWidthMul: 0.88, eyeSpacing: -2, browHeight: 2, yaw: -1,
              skin: 'pale', hair: 'gray', eye: 'closed', nose: 'straight', mouth: 'firm',
              beard: 'whitelong', beardLen: 17, hat: 'gwan', color: 'black', robe: 'blue', bg: 'blue', bgStyle: 5 },
  '주환':   { headW: 48, headH: 50, face: 0, jaw: 1, jawWidthMul: 1.04, eyeSpacing: 1, browHeight: -1, yaw: -2,
              skin: 'tan', hair: 'black', eye: 'big', nose: 'straight', mouth: 'open',
              beard: 'mustache', hat: 'helm', color: 'steel', robe: 'crimson', bg: 'crimson', bgStyle: 3 },
  '주연':   { headW: 50, headH: 53, face: 1, jaw: 1, jawWidthMul: 1.02, eyeSpacing: 0, browHeight: 0, yaw: 3,
              skin: 'tan', hair: 'black', eye: 'open', nose: 'straight', mouth: 'closed',
              beard: 'full', hat: 'helm', color: 'blue', robe: 'blue', bg: 'teal', bgStyle: 0 },
  '손유':   { headW: 49, headH: 51, face: 0, jaw: 0, jawWidthMul: 1.05, eyeSpacing: 1, browHeight: 1, yaw: 0,
              skin: 'pale', hair: 'black', eye: 'open', nose: 'straight', mouth: 'smile',
              beard: 'goatee', hat: 'warcloth', color: 'red', robe: 'red', bg: 'red', bgStyle: 2 },
  '제갈각': { headW: 46, headH: 59, face: 1, jaw: 2, jawWidthMul: 0.92, eyeSpacing: -1, browHeight: 1, yaw: -3,
              skin: 'pale', hair: 'black', eye: 'sanpaku', brow: 'raised', nose: 'long', mouth: 'smile',
              beard: 'goatee', hat: 'gwan', color: 'purple', robe: 'purple', bg: 'purple', bgStyle: 3 },
  '육항':   { headW: 46, headH: 55, face: 1, jaw: 2, jawWidthMul: 0.91, eyeSpacing: -2, browHeight: 2, yaw: -1,
              skin: 'pale', hair: 'black', eye: 'gentle', brow: 'arch', nose: 'straight', mouth: 'closed',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'green', bg: 'green', bgStyle: 2 },
  '보즐':   { headW: 47, headH: 53, face: 4, jaw: 2, jawWidthMul: 0.93, eyeSpacing: 1, browHeight: 1, yaw: 4,
              skin: 'sallow', hair: 'black', eye: 'gentle', nose: 'small', mouth: 'smile',
              beard: 'goatee', hat: 'wrap', color: 'teal', robe: 'teal', bg: 'teal', bgStyle: 5 },

  /* ═══ 동탁 · 서량 · 원가 ══════════════════════════════════════════ */
  '동탁':   { headW: 59, headH: 46, face: 0, jaw: 0, jawWidthMul: 1.13, eyeSpacing: 3, browHeight: -1, cheekY: 0.04, yaw: 2,
              skin: 'sallow', hair: 'black', eye: 'big', brow: 'thick', nose: 'wide', mouth: 'open',
              beard: 'full', hat: 'crown', color: 'gold', robe: 'purple', bg: 'black', bgStyle: 0, fat: 1, irisDark: 1 },
  '여포':   { headW: 48, headH: 54, face: 1, jaw: 1, jawWidthMul: 1.02, eyeSpacing: -2, browHeight: -1, yaw: -5,
              skin: 'pale', hair: 'brown', eye: 'sharp', brow: 'raised', nose: 'straight', mouth: 'frown',
              beard: 'mustache', hat: 'phoenixhelm', color: 'gold', robe: 'crimson', bg: 'crimson', bgStyle: 2 },
  '진궁':   { headW: 45, headH: 56, face: 4, jaw: 2, jawWidthMul: 0.90, eyeSpacing: -1, browHeight: 1, yaw: 3,
              skin: 'pale', hair: 'black', eye: 'glare', brow: 'flat', nose: 'straight', mouth: 'firm',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'blue', bg: 'blue', bgStyle: 5 },
  '고순':   { headW: 51, headH: 52, face: 2, jaw: 1, jawWidthMul: 1.06, eyeSpacing: -1, browHeight: -2, yaw: 0,
              skin: 'bronze', hair: 'black', eye: 'glare', brow: 'flat', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'facehelm', color: 'iron', robe: 'black', bg: 'brown', bgStyle: 0 },
  '이유':   { headW: 44, headH: 55, face: 4, jaw: 2, jawWidthMul: 0.87, eyeSpacing: -3, browHeight: 1, yaw: 4,
              skin: 'sallow', hair: 'black', eye: 'thin', brow: 'raised', nose: 'hook', mouth: 'frown',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'black', bg: 'purple', bgStyle: 3 },
  '이각':   { headW: 53, headH: 50, face: 2, jaw: 1, jawWidthMul: 1.10, eyeSpacing: 2, browHeight: -2, yaw: -2,
              skin: 'dark', hair: 'black', eye: 'sanpaku', nose: 'wide', mouth: 'open',
              beard: 'bushy', hat: 'warcloth', color: 'brown', robe: 'brown', bg: 'brown', bgStyle: 4, scar: 1 },
  '곽사':   { headW: 52, headH: 48, face: 3, jaw: 1, jawWidthMul: 1.08, eyeSpacing: 1, browHeight: -1, yaw: 3,
              skin: 'dark', hair: 'black', eye: 'glare', nose: 'wide', mouth: 'frown',
              beard: 'whisker', hat: 'warcloth', color: 'red', robe: 'red', bg: 'red', bgStyle: 1 },
  '화웅':   { headW: 56, headH: 51, face: 3, jaw: 1, jawWidthMul: 1.14, eyeSpacing: 2, browHeight: -2, yaw: -1,
              skin: 'bronze', hair: 'black', eye: 'big', brow: 'thick', nose: 'wide', mouth: 'open',
              beard: 'bushy', hat: 'helm', color: 'bronze', robe: 'brown', bg: 'gold', bgStyle: 0 },
  '서영':   { headW: 50, headH: 53, face: 2, jaw: 1, jawWidthMul: 1.04, eyeSpacing: 0, browHeight: -1, yaw: 2,
              skin: 'bronze', hair: 'black', eye: 'sharp', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'steel', robe: 'iron', bg: 'silver', bgStyle: 3 },
  '장제':   { headW: 49, headH: 50, face: 0, jaw: 1, jawWidthMul: 1.03, eyeSpacing: 1, browHeight: 0, yaw: -3,
              skin: 'tan', hair: 'black', eye: 'open', nose: 'straight', mouth: 'closed',
              beard: 'full', hat: 'helm', color: 'bronze', robe: 'yellow', bg: 'gold', bgStyle: 1 },
  '마등':   { headW: 54, headH: 54, face: 2, jaw: 1, jawWidthMul: 1.09, eyeSpacing: 0, browHeight: -1, yaw: -2,
              skin: 'bronze', hair: 'gray', eye: 'sharp', brow: 'thick', nose: 'hook', mouth: 'firm',
              beard: 'whitelong', beardLen: 18, hat: 'helm', color: 'gold', robe: 'white', bg: 'gold', bgStyle: 0 },
  '한수':   { headW: 50, headH: 56, face: 1, jaw: 1, jawWidthMul: 1.00, eyeSpacing: -1, browHeight: 1, yaw: 4,
              skin: 'sallow', hair: 'gray', eye: 'thin', nose: 'long', mouth: 'frown',
              beard: 'whitelong', beardLen: 15, hat: 'wrap', color: 'brown', robe: 'brown', bg: 'brown', bgStyle: 5 },
  '원소':   { headW: 50, headH: 57, face: 1, jaw: 1, jawWidthMul: 1.02, eyeSpacing: 0, browHeight: 2, cheekY: -0.02, yaw: -1,
              skin: 'pale', hair: 'black', eye: 'gentle', brow: 'arch', nose: 'straight', mouth: 'closed',
              beard: 'long', beardLen: 17, hat: 'crown', color: 'gold', robe: 'blue', bg: 'blue', bgStyle: 2 },
  '안량':   { headW: 53, headH: 51, face: 2, jaw: 1, jawWidthMul: 1.10, eyeSpacing: 1, browHeight: -2, yaw: -3,
              skin: 'bronze', hair: 'black', eye: 'big', brow: 'thick', nose: 'wide', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'steel', robe: 'blue', bg: 'blue', bgStyle: 0 },
  '문추':   { headW: 55, headH: 49, face: 3, jaw: 1, jawWidthMul: 1.12, eyeSpacing: 2, browHeight: -2, yaw: 3,
              skin: 'dark', hair: 'black', eye: 'glare', brow: 'thick', nose: 'wide', mouth: 'open',
              beard: 'bushy', hat: 'helm', color: 'iron', robe: 'blue', bg: 'teal', bgStyle: 4 },
  '전풍':   { headW: 44, headH: 58, face: 4, jaw: 2, jawWidthMul: 0.86, eyeSpacing: -2, browHeight: 0, yaw: 2,
              skin: 'pale', hair: 'gray', eye: 'glare', brow: 'raised', nose: 'long', mouth: 'frown',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'white', bg: 'silver', bgStyle: 5 },
  '저수':   { headW: 46, headH: 57, face: 1, jaw: 2, jawWidthMul: 0.92, eyeSpacing: -1, browHeight: 2, yaw: -2,
              skin: 'pale', hair: 'gray', eye: 'thin', nose: 'straight', mouth: 'firm',
              beard: 'whitelong', beardLen: 16, hat: 'gwan', color: 'black', robe: 'blue', bg: 'blue', bgStyle: 3 },
  '심배':   { headW: 49, headH: 54, face: 2, jaw: 1, jawWidthMul: 1.01, eyeSpacing: -2, browHeight: -1, yaw: 1,
              skin: 'tan', hair: 'black', eye: 'glare', brow: 'flat', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'gwan', color: 'black', robe: 'teal', bg: 'teal', bgStyle: 0 },
  '곽도':   { headW: 47, headH: 52, face: 4, jaw: 2, jawWidthMul: 0.94, eyeSpacing: 2, browHeight: 1, yaw: 4,
              skin: 'sallow', hair: 'black', eye: 'sanpaku', brow: 'raised', nose: 'hook', mouth: 'smile',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'purple', bg: 'purple', bgStyle: 5 },
  '고람':   { headW: 51, headH: 51, face: 2, jaw: 1, jawWidthMul: 1.07, eyeSpacing: 0, browHeight: -1, yaw: -2,
              skin: 'tan', hair: 'black', eye: 'sharp', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'blue', robe: 'blue', bg: 'blue', bgStyle: 1 },
  '원담':   { headW: 49, headH: 55, face: 1, jaw: 1, jawWidthMul: 1.03, eyeSpacing: -1, browHeight: 0, yaw: 2,
              skin: 'pale', hair: 'black', eye: 'sharp', nose: 'straight', mouth: 'frown',
              beard: 'goatee', hat: 'helm', color: 'gold', robe: 'blue', bg: 'blue', bgStyle: 3, young: 1 },
  '원상':   { headW: 46, headH: 53, face: 1, jaw: 2, jawWidthMul: 0.96, eyeSpacing: 0, browHeight: 1, yaw: -3,
              skin: 'pale', hair: 'black', eye: 'open', brow: 'arch', nose: 'straight', mouth: 'smile',
              beard: 'none', hat: 'crown', color: 'gold', robe: 'teal', bg: 'teal', bgStyle: 2, young: 1 },
  '원희':   { headW: 48, headH: 54, face: 1, jaw: 0, jawWidthMul: 0.99, eyeSpacing: 1, browHeight: 1, yaw: 1,
              skin: 'pale', hair: 'black', eye: 'gentle', nose: 'straight', mouth: 'closed',
              beard: 'mustache', hat: 'gwan', color: 'blue', robe: 'blue', bg: 'purple', bgStyle: 1, young: 1 },
  '원술':   { headW: 55, headH: 48, face: 0, jaw: 0, jawWidthMul: 1.11, eyeSpacing: 2, browHeight: 1, cheekY: 0.03, yaw: 0,
              skin: 'pale', hair: 'black', eye: 'sleepy', brow: 'drooped', nose: 'wide', mouth: 'frown',
              beard: 'full', hat: 'crown', color: 'gold', robe: 'gold', bg: 'gold', bgStyle: 2, fat: 1 },
  '기령':   { headW: 53, headH: 52, face: 3, jaw: 1, jawWidthMul: 1.09, eyeSpacing: 1, browHeight: -2, yaw: -1,
              skin: 'bronze', hair: 'black', eye: 'big', brow: 'thick', nose: 'wide', mouth: 'open',
              beard: 'bushy', hat: 'helm', color: 'bronze', robe: 'yellow', bg: 'gold', bgStyle: 0 },
  '뇌박':   { headW: 50, headH: 47, face: 2, jaw: 1, jawWidthMul: 1.05, eyeSpacing: 2, browHeight: -1, yaw: 3,
              skin: 'dark', hair: 'black', eye: 'glare', nose: 'wide', mouth: 'frown',
              beard: 'whisker', hat: 'topknot', color: 'brown', robe: 'brown', bg: 'brown', bgStyle: 4 },

  /* ═══ 형주 · 익주 · 하북 · 남방 · 그 밖의 군웅 ════════════════════ */
  '공손찬': { headW: 49, headH: 55, face: 1, jaw: 1, jawWidthMul: 1.04, eyeSpacing: -1, browHeight: -1, yaw: -4,
              skin: 'pale', hair: 'brown', eye: 'sharp', brow: 'raised', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'silver', robe: 'white', bg: 'blue', bgStyle: 2 },
  '엄강':   { headW: 51, headH: 50, face: 2, jaw: 1, jawWidthMul: 1.06, eyeSpacing: 1, browHeight: -1, yaw: 2,
              skin: 'tan', hair: 'black', eye: 'open', nose: 'wide', mouth: 'closed',
              beard: 'full', hat: 'helm', color: 'steel', robe: 'white', bg: 'silver', bgStyle: 0 },
  '전해':   { headW: 48, headH: 52, face: 1, jaw: 0, jawWidthMul: 1.00, eyeSpacing: 0, browHeight: 0, yaw: -1,
              skin: 'tan', hair: 'black', eye: 'open', nose: 'straight', mouth: 'closed',
              beard: 'goatee', hat: 'warcloth', color: 'blue', robe: 'blue', bg: 'blue', bgStyle: 4 },
  '유표':   { headW: 47, headH: 60, face: 1, jaw: 0, jawWidthMul: 0.95, eyeSpacing: 0, browHeight: 2, yaw: 1,
              skin: 'pale', hair: 'gray', eye: 'gentle', brow: 'arch', nose: 'long', mouth: 'closed',
              beard: 'whitelong', beardLen: 19, hat: 'crown', color: 'gold', robe: 'green', bg: 'green', bgStyle: 2 },
  '채모':   { headW: 52, headH: 51, face: 2, jaw: 1, jawWidthMul: 1.07, eyeSpacing: 2, browHeight: -1, yaw: 3,
              skin: 'tan', hair: 'black', eye: 'sanpaku', brow: 'raised', nose: 'hook', mouth: 'smile',
              beard: 'full', hat: 'helm', color: 'bronze', robe: 'green', bg: 'teal', bgStyle: 3 },
  '장윤':   { headW: 49, headH: 49, face: 0, jaw: 0, jawWidthMul: 1.02, eyeSpacing: 1, browHeight: 0, yaw: -2,
              skin: 'tan', hair: 'black', eye: 'thin', nose: 'straight', mouth: 'frown',
              beard: 'mustache', hat: 'warcloth', color: 'green', robe: 'green', bg: 'green', bgStyle: 1 },
  '황조':   { headW: 53, headH: 53, face: 2, jaw: 1, jawWidthMul: 1.08, eyeSpacing: 0, browHeight: -2, yaw: 2,
              skin: 'bronze', hair: 'gray', eye: 'glare', brow: 'thick', nose: 'wide', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'bronze', robe: 'brown', bg: 'brown', bgStyle: 0 },
  '괴량':   { headW: 45, headH: 55, face: 4, jaw: 2, jawWidthMul: 0.91, eyeSpacing: -1, browHeight: 1, yaw: -2,
              skin: 'pale', hair: 'black', eye: 'thin', nose: 'straight', mouth: 'closed',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'green', bg: 'green', bgStyle: 5 },
  '괴월':   { headW: 46, headH: 56, face: 4, jaw: 2, jawWidthMul: 0.93, eyeSpacing: 1, browHeight: 2, yaw: 2,
              skin: 'pale', hair: 'black', eye: 'closed', nose: 'straight', mouth: 'smile',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'teal', bg: 'teal', bgStyle: 5 },
  '유기':   { headW: 44, headH: 53, face: 4, jaw: 2, jawWidthMul: 0.89, eyeSpacing: 0, browHeight: 2, yaw: -3,
              skin: 'pale', hair: 'black', eye: 'sleepy', brow: 'drooped', nose: 'small', mouth: 'closed',
              beard: 'none', hat: 'silk', color: 'white', robe: 'white', bg: 'green', bgStyle: 1, young: 1 },
  '유종':   { headW: 47, headH: 46, face: 0, jaw: 2, jawWidthMul: 0.97, eyeSpacing: 1, browHeight: 2, yaw: 1,
              skin: 'pale', hair: 'black', eye: 'big', brow: 'arch', nose: 'small', mouth: 'open',
              beard: 'none', hat: 'gwan', color: 'green', robe: 'green', bg: 'teal', bgStyle: 2, young: 1 },
  '유장':   { headW: 53, headH: 49, face: 0, jaw: 0, jawWidthMul: 1.07, eyeSpacing: 2, browHeight: 2, cheekY: 0.03, yaw: 0,
              skin: 'pale', hair: 'black', eye: 'sleepy', brow: 'drooped', nose: 'wide', mouth: 'closed',
              beard: 'goatee', hat: 'crown', color: 'gold', robe: 'teal', bg: 'teal', bgStyle: 2, fat: 1 },
  '장임':   { headW: 50, headH: 54, face: 1, jaw: 1, jawWidthMul: 1.05, eyeSpacing: -1, browHeight: -1, yaw: -3,
              skin: 'bronze', hair: 'black', eye: 'sharp', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'steel', robe: 'blue', bg: 'blue', bgStyle: 0 },
  '엄안':   { headW: 52, headH: 55, face: 2, jaw: 1, jawWidthMul: 1.06, eyeSpacing: 0, browHeight: -1, yaw: 3,
              skin: 'bronze', hair: 'white', eye: 'glare', brow: 'thick', nose: 'hook', mouth: 'firm',
              beard: 'whitelong', beardLen: 21, hat: 'helm', color: 'bronze', robe: 'brown', bg: 'gold', bgStyle: 4 },
  '오의':   { headW: 49, headH: 52, face: 1, jaw: 1, jawWidthMul: 1.01, eyeSpacing: 0, browHeight: 0, yaw: -1,
              skin: 'tan', hair: 'black', eye: 'open', nose: 'straight', mouth: 'closed',
              beard: 'full', hat: 'helm', color: 'blue', robe: 'teal', bg: 'blue', bgStyle: 1 },
  '이엄':   { headW: 48, headH: 56, face: 1, jaw: 2, jawWidthMul: 0.96, eyeSpacing: -2, browHeight: 1, yaw: 2,
              skin: 'pale', hair: 'black', eye: 'thin', brow: 'raised', nose: 'long', mouth: 'firm',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'purple', bg: 'purple', bgStyle: 3 },
  '황권':   { headW: 47, headH: 55, face: 1, jaw: 0, jawWidthMul: 0.98, eyeSpacing: -1, browHeight: 1, yaw: -2,
              skin: 'pale', hair: 'black', eye: 'glare', brow: 'flat', nose: 'straight', mouth: 'firm',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'blue', bg: 'blue', bgStyle: 5 },
  '장로':   { headW: 48, headH: 57, face: 1, jaw: 2, jawWidthMul: 0.94, eyeSpacing: 0, browHeight: 2, yaw: 1,
              skin: 'sallow', hair: 'gray', eye: 'closed', nose: 'straight', mouth: 'smile',
              beard: 'whitelong', beardLen: 18, hat: 'daoist', color: 'yellow', robe: 'yellow', bg: 'yellow', bgStyle: 2 },
  '양송':   { headW: 46, headH: 48, face: 0, jaw: 2, jawWidthMul: 0.95, eyeSpacing: 3, browHeight: 1, yaw: 4,
              skin: 'sallow', hair: 'black', eye: 'sanpaku', brow: 'raised', nose: 'hook', mouth: 'smile',
              beard: 'mustache', hat: 'gwan', color: 'yellow', robe: 'yellow', bg: 'brown', bgStyle: 4 },
  '양임':   { headW: 51, headH: 51, face: 2, jaw: 1, jawWidthMul: 1.04, eyeSpacing: 1, browHeight: -1, yaw: -2,
              skin: 'bronze', hair: 'black', eye: 'sharp', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'warcloth', color: 'yellow', robe: 'brown', bg: 'yellow', bgStyle: 0 },
  '도겸':   { headW: 47, headH: 58, face: 1, jaw: 2, jawWidthMul: 0.92, eyeSpacing: -1, browHeight: 1, yaw: 2,
              skin: 'sallow', hair: 'white', eye: 'droop', nose: 'long', mouth: 'frown',
              beard: 'whitelong', beardLen: 20, hat: 'gwan', color: 'black', robe: 'brown', bg: 'brown', bgStyle: 1 },
  '조표':   { headW: 51, headH: 50, face: 2, jaw: 1, jawWidthMul: 1.05, eyeSpacing: 2, browHeight: -1, yaw: -3,
              skin: 'tan', hair: 'black', eye: 'glare', nose: 'wide', mouth: 'frown',
              beard: 'full', hat: 'helm', color: 'steel', robe: 'crimson', bg: 'crimson', bgStyle: 3 },
  '진등':   { headW: 45, headH: 53, face: 4, jaw: 2, jawWidthMul: 0.90, eyeSpacing: -1, browHeight: 2, yaw: -4,
              skin: 'pale', hair: 'black', eye: 'sharp', brow: 'arch', nose: 'straight', mouth: 'smile',
              beard: 'none', hat: 'silk', color: 'blue', robe: 'blue', bg: 'teal', bgStyle: 2, young: 1 },
  '진규':   { headW: 47, headH: 56, face: 1, jaw: 2, jawWidthMul: 0.93, eyeSpacing: 0, browHeight: 1, yaw: 1,
              skin: 'pale', hair: 'gray', eye: 'thin', nose: 'straight', mouth: 'smile',
              beard: 'whitelong', beardLen: 16, hat: 'gwan', color: 'black', robe: 'blue', bg: 'blue', bgStyle: 0 },
  '한복':   { headW: 50, headH: 48, face: 0, jaw: 0, jawWidthMul: 1.02, eyeSpacing: 2, browHeight: 2, yaw: 3,
              skin: 'pale', hair: 'black', eye: 'sleepy', brow: 'drooped', nose: 'small', mouth: 'open',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'gold', bg: 'gold', bgStyle: 4 },
  '국의':   { headW: 50, headH: 53, face: 2, jaw: 1, jawWidthMul: 1.06, eyeSpacing: -1, browHeight: -2, yaw: -2,
              skin: 'bronze', hair: 'black', eye: 'sharp', brow: 'raised', nose: 'straight', mouth: 'firm',
              beard: 'goatee', hat: 'helm', color: 'iron', robe: 'iron', bg: 'silver', bgStyle: 0 },
  '공융':   { headW: 46, headH: 57, face: 4, jaw: 2, jawWidthMul: 0.91, eyeSpacing: 0, browHeight: 2, yaw: -1,
              skin: 'pale', hair: 'gray', eye: 'gentle', brow: 'arch', nose: 'straight', mouth: 'smile',
              beard: 'whitelong', beardLen: 17, hat: 'gwan', color: 'black', robe: 'white', bg: 'teal', bgStyle: 2, shoulder: 'court' },
  '왕랑':   { headW: 49, headH: 56, face: 1, jaw: 0, jawWidthMul: 0.99, eyeSpacing: 1, browHeight: 1, yaw: 2,
              skin: 'pale', hair: 'gray', eye: 'thin', nose: 'straight', mouth: 'firm',
              beard: 'whitelong', beardLen: 19, hat: 'gwan', color: 'black', robe: 'purple', bg: 'purple', bgStyle: 1, shoulder: 'court' },
  '엄백호': { headW: 54, headH: 47, face: 3, jaw: 1, jawWidthMul: 1.10, eyeSpacing: 2, browHeight: -2, yaw: 3,
              skin: 'dark', hair: 'black', eye: 'big', brow: 'thick', nose: 'wide', mouth: 'open',
              beard: 'bushy', hat: 'topknot', color: 'red', robe: 'red', bg: 'red', bgStyle: 4 },
  '유요':   { headW: 48, headH: 54, face: 1, jaw: 0, jawWidthMul: 0.97, eyeSpacing: 0, browHeight: 1, yaw: -1,
              skin: 'pale', hair: 'black', eye: 'gentle', nose: 'straight', mouth: 'closed',
              beard: 'goatee', hat: 'gwan', color: 'black', robe: 'green', bg: 'green', bgStyle: 3 },
  '장영':   { headW: 51, headH: 49, face: 2, jaw: 1, jawWidthMul: 1.04, eyeSpacing: 1, browHeight: -1, yaw: 2,
              skin: 'tan', hair: 'black', eye: 'open', nose: 'straight', mouth: 'firm',
              beard: 'mustache', hat: 'helm', color: 'steel', robe: 'green', bg: 'teal', bgStyle: 0 },
  '사섭':   { headW: 48, headH: 58, face: 1, jaw: 2, jawWidthMul: 0.95, eyeSpacing: -1, browHeight: 2, cheekY: -0.02, yaw: -2,
              skin: 'tan', hair: 'white', eye: 'gentle', brow: 'arch', nose: 'straight', mouth: 'smile',
              beard: 'whitelong', beardLen: 20, hat: 'gwan', color: 'black', robe: 'teal', bg: 'teal', bgStyle: 2, shoulder: 'court' },
  '장연':   { headW: 47, headH: 50, face: 1, jaw: 2, jawWidthMul: 0.96, eyeSpacing: -2, browHeight: -1, yaw: -4,
              skin: 'dark', hair: 'black', eye: 'sharp', nose: 'small', mouth: 'firm',
              beard: 'mustache', hat: 'wrap', color: 'black', robe: 'black', bg: 'brown', bgStyle: 5 },
  '맹획':   { headW: 55, headH: 50, face: 3, jaw: 1, jawWidthMul: 1.12, eyeSpacing: 2, browHeight: -2, yaw: 1,
              skin: 'dark', hair: 'black', eye: 'big', brow: 'thick', nose: 'wide', mouth: 'open',
              beard: 'bushy', hat: 'feather', color: 'red', robe: 'brown', bg: 'green', bgStyle: 0, earring: 1, irisDark: 1 },
  '김선':   { headW: 49, headH: 51, face: 0, jaw: 0, jawWidthMul: 1.01, eyeSpacing: 1, browHeight: 0, yaw: 2,
              skin: 'tan', hair: 'black', eye: 'open', nose: 'straight', mouth: 'closed',
              beard: 'goatee', hat: 'gwan', color: 'brown', robe: 'brown', bg: 'brown', bgStyle: 3 },
  '한현':   { headW: 52, headH: 48, face: 0, jaw: 0, jawWidthMul: 1.05, eyeSpacing: 2, browHeight: 1, yaw: -2,
              skin: 'sallow', hair: 'black', eye: 'glare', brow: 'raised', nose: 'wide', mouth: 'frown',
              beard: 'full', hat: 'gwan', color: 'black', robe: 'red', bg: 'red', bgStyle: 1, fat: 1 },
  '조범':   { headW: 47, headH: 52, face: 1, jaw: 0, jawWidthMul: 0.98, eyeSpacing: 0, browHeight: 1, yaw: 3,
              skin: 'pale', hair: 'black', eye: 'thin', nose: 'straight', mouth: 'smile',
              beard: 'mustache', hat: 'gwan', color: 'purple', robe: 'purple', bg: 'purple', bgStyle: 4 },
  '유도':   { headW: 50, headH: 52, face: 0, jaw: 0, jawWidthMul: 1.03, eyeSpacing: -1, browHeight: 1, yaw: -1,
              skin: 'tan', hair: 'gray', eye: 'gentle', nose: 'straight', mouth: 'closed',
              beard: 'full', hat: 'gwan', color: 'black', robe: 'teal', bg: 'green', bgStyle: 5 },
  '사마휘': { headW: 45, headH: 59, face: 4, jaw: 2, jawWidthMul: 0.88, eyeSpacing: 0, browHeight: 2, yaw: 2,
              skin: 'pale', hair: 'white', eye: 'smile', brow: 'arch', nose: 'straight', mouth: 'smile',
              beard: 'whitelong', beardLen: 22, hat: 'silk', color: 'white', robe: 'white', bg: 'green', bgStyle: 2, fan: 1 },
  '공손탁': { headW: 51, headH: 53, face: 2, jaw: 1, jawWidthMul: 1.05, eyeSpacing: 0, browHeight: -1, yaw: 1,
              skin: 'bronze', hair: 'black', eye: 'thin', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'fur', color: 'brown', robe: 'brown', bg: 'silver', bgStyle: 0 },
  '포신':   { headW: 50, headH: 51, face: 2, jaw: 1, jawWidthMul: 1.03, eyeSpacing: -1, browHeight: 0, yaw: -3,
              skin: 'tan', hair: 'black', eye: 'open', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'steel', robe: 'blue', bg: 'blue', bgStyle: 3 },
  '왕윤':   { headW: 46, headH: 58, face: 1, jaw: 2, jawWidthMul: 0.90, eyeSpacing: -2, browHeight: 2, yaw: -1,
              skin: 'pale', hair: 'gray', eye: 'glare', brow: 'flat', nose: 'long', mouth: 'firm',
              beard: 'whitelong', beardLen: 18, hat: 'gwan', color: 'black', robe: 'crimson', bg: 'crimson', bgStyle: 2, shoulder: 'court' },
  '허유':   { headW: 48, headH: 51, face: 0, jaw: 2, jawWidthMul: 0.99, eyeSpacing: 3, browHeight: 1, yaw: 4,
              skin: 'sallow', hair: 'black', eye: 'sanpaku', brow: 'raised', nose: 'hook', mouth: 'smile',
              beard: 'goatee', hat: 'wrap', color: 'brown', robe: 'brown', bg: 'gold', bgStyle: 4 },
  '공손강': { headW: 50, headH: 54, face: 1, jaw: 1, jawWidthMul: 1.06, eyeSpacing: 1, browHeight: -1, yaw: -2,
              skin: 'bronze', hair: 'black', eye: 'sharp', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'fur', color: 'iron', robe: 'iron', bg: 'silver', bgStyle: 3 },
  '진림':   { headW: 44, headH: 55, face: 4, jaw: 2, jawWidthMul: 0.87, eyeSpacing: 0, browHeight: 2, yaw: 3,
              skin: 'pale', hair: 'black', eye: 'thin', brow: 'arch', nose: 'straight', mouth: 'smile',
              beard: 'goatee', hat: 'silk', color: 'white', robe: 'white', bg: 'blue', bgStyle: 5 },
  '장각':   { headW: 49, headH: 60, face: 1, jaw: 2, jawWidthMul: 0.94, eyeSpacing: -2, browHeight: 1, cheekY: -0.03, yaw: 0,
              skin: 'sallow', hair: 'gray', eye: 'glare', brow: 'raised', nose: 'hook', mouth: 'firm',
              beard: 'whitelong', beardLen: 23, hat: 'daoist', color: 'yellow', robe: 'yellow', bg: 'black', bgStyle: 2, irisDark: 1 },
  '장보':   { headW: 51, headH: 53, face: 2, jaw: 1, jawWidthMul: 1.02, eyeSpacing: 0, browHeight: -1, yaw: -3,
              skin: 'sallow', hair: 'black', eye: 'sharp', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'daoist', color: 'yellow', robe: 'yellow', bg: 'brown', bgStyle: 0 },
  '장량':   { headW: 52, headH: 51, face: 2, jaw: 1, jawWidthMul: 1.04, eyeSpacing: 1, browHeight: -2, yaw: 3,
              skin: 'sallow', hair: 'black', eye: 'glare', nose: 'wide', mouth: 'open',
              beard: 'goatee', hat: 'daoist', color: 'yellow', robe: 'brown', bg: 'yellow', bgStyle: 1 },
  '황보숭': { headW: 52, headH: 56, face: 2, jaw: 1, jawWidthMul: 1.07, eyeSpacing: -1, browHeight: 0, yaw: -2,
              skin: 'tan', hair: 'gray', eye: 'sharp', brow: 'flat', nose: 'straight', mouth: 'firm',
              beard: 'whitelong', beardLen: 17, hat: 'facehelm', color: 'gold', robe: 'crimson', bg: 'crimson', bgStyle: 0 },
  '주준':   { headW: 50, headH: 55, face: 1, jaw: 1, jawWidthMul: 1.01, eyeSpacing: 0, browHeight: 1, yaw: 2,
              skin: 'tan', hair: 'gray', eye: 'open', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'gold', robe: 'blue', bg: 'blue', bgStyle: 1 },
  '노식':   { headW: 47, headH: 59, face: 1, jaw: 2, jawWidthMul: 0.93, eyeSpacing: -1, browHeight: 2, yaw: -1,
              skin: 'pale', hair: 'gray', eye: 'gentle', brow: 'arch', nose: 'long', mouth: 'closed',
              beard: 'whitelong', beardLen: 21, hat: 'gwan', color: 'black', robe: 'white', bg: 'teal', bgStyle: 2, shoulder: 'court' },
  '하진':   { headW: 56, headH: 49, face: 3, jaw: 1, jawWidthMul: 1.11, eyeSpacing: 2, browHeight: 1, cheekY: 0.03, yaw: 1,
              skin: 'tan', hair: 'black', eye: 'sleepy', brow: 'drooped', nose: 'wide', mouth: 'open',
              beard: 'full', hat: 'gwan', color: 'gold', robe: 'purple', bg: 'purple', bgStyle: 4, fat: 1 },
  '장수':   { headW: 48, headH: 52, face: 1, jaw: 1, jawWidthMul: 1.00, eyeSpacing: -1, browHeight: -1, yaw: -4,
              skin: 'bronze', hair: 'black', eye: 'sharp', nose: 'straight', mouth: 'firm',
              beard: 'mustache', hat: 'phoenixhelm', color: 'bronze', robe: 'red', bg: 'gold', bgStyle: 3, young: 1 },
  '관구검': { headW: 51, headH: 54, face: 2, jaw: 1, jawWidthMul: 1.05, eyeSpacing: 0, browHeight: -1, yaw: 2,
              skin: 'tan', hair: 'black', eye: 'glare', brow: 'flat', nose: 'straight', mouth: 'firm',
              beard: 'full', hat: 'facehelm', color: 'steel', robe: 'iron', bg: 'blue', bgStyle: 0 },
  '제갈탄': { headW: 49, headH: 56, face: 1, jaw: 1, jawWidthMul: 0.98, eyeSpacing: -2, browHeight: 1, yaw: -2,
              skin: 'pale', hair: 'black', eye: 'sharp', nose: 'long', mouth: 'firm',
              beard: 'full', hat: 'helm', color: 'silver', robe: 'purple', bg: 'purple', bgStyle: 5 },
};
